### ISSUE TITLE
KeyError when parsing the config.ini

### ISSUE THREAD

**Issue by yangyxt** [vincentiusmartin/QBiC-Pred#10]
Hit a KeyError when parsing the config.ini. 
See the log screenshot as below:
![image](https://user-images.githubusercontent.com/40780228/84035600-910b1080-a9ce-11ea-8ff4-defd8f5ee40f.png)
Here is the config.ini content posted as a screenshot:
![image](https://user-images.githubusercontent.com/40780228/84035683-b435c000-a9ce-11ea-83a9-2d99dea4cd70.png)
I see the headers are right. Don't know why this happened.

**Comment by yangyxt** [comment]
I just found out that's because the config.ini file at the same dir cannot be identified. Using abs path of config.ini file fix this. But why do I need to use full path here? And I also recommend add a small check on the config.ini file.

![image](https://user-images.githubusercontent.com/40780228/84038184-31aeff80-a9d2-11ea-95d5-a64d99fdd445.png)

**Comment by vincentiusmartin** [comment]
Thanks for reaching out. It is important to note that path is relative to the current working directory. I see that you ran the script using the absolute path, which means you could run it anywhere and thus, you need the full config path. 
Complete explanation: https://stackoverflow.com/questions/13800515/cant-load-relative-config-file-using-configparser-from-sub-directory

**Comment by vincentiusmartin** [comment]
Small check on the config file is definitely a good suggestion, I just applied it.
